postgresql: Add corner case for DRBD conversion
If the prior instance of postgresql was running there
is no way to kill it after the conversion to DRBD.

This adds the corner case to stop the old daemon after
the data directory has been migrated.

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>

diff --git a/meta-openstack/recipes-support/postgresql/postgresql/postgresql b/meta-openstack/recipes-support/postgresql/postgresql/postgresql
--- a/meta-openstack/recipes-support/postgresql/postgresql/postgresql
+++ b/meta-openstack/recipes-support/postgresql/postgresql/postgresql
@@ -55,7 +55,16 @@ stop ()
     if [ $? -eq 0 ]; then
         echo "done."
     else
-        echo "failed."
+	if [ -f /etc/postgresql/postmaster.pid -a "$datadir" != "/etc/postgresql" ] ; then
+	    # Special case for transition 
+	    sudo -u postgres /usr/bin/pg_ctl stop -w -D /etc/postgresql -m fast -s
+	fi
+        if ! pidof ${DAEMON} > /dev/null; then
+	    echo "done."
+	else
+            echo "failed."
+	    exit 1
+	fi
     fi
 }
 
