openstack initscript: add reset
Some of the openstack data is associated with external resources
(ie glance may have external files), we explicitly invoke the delete commands on those
in additional to dropping and recreating the databases.

Signed-off-by: Amy Fong <amy.fong@windriver.com>

diff --git a/meta-openstack/recipes-devtools/python/python-cinder/cinder-volume b/meta-openstack/recipes-devtools/python/python-cinder/cinder-volume
--- a/meta-openstack/recipes-devtools/python/python-cinder/cinder-volume
+++ b/meta-openstack/recipes-devtools/python/python-cinder/cinder-volume
@@ -69,6 +69,39 @@ status()
     echo "$DESC is not running"
 }
 
+reset()
+{
+    . /etc/nova/openrc
+
+    # Cleanup cinder volume
+    simple_delete "cinder list --all-tenant" "cinder delete" 1 "cinder volume"
+
+    # Cleanup cinder backup
+    simple_delete "cinder backup-list" "cinder backup-delete" 1 "cinder backup"
+
+    stop
+
+    if ! pidof postmaster > /dev/null; then
+        /etc/init.d/postgresql-init
+        /etc/init.d/postgresql start
+    fi
+    [ ! -d /var/log/cinder ] && mkdir /var/log/cinder
+    sudo -u postgres dropdb cinder
+    sudo -u postgres createdb cinder
+    cinder-manage db sync
+
+    if [ ! -f /etc/cinder/nfs_shares ]; then
+        /bin/bash /etc/cinder/drivers/nfs_setup.sh
+    fi
+
+    # Create Cinder glusterfs_share config file with default glusterfs server
+    if [ ! -f /etc/cinder/glusterfs_shares ] && [ -f /usr/sbin/glusterfsd ]; then
+        /bin/bash /etc/cinder/drivers/glusterfs_setup.sh
+    fi
+
+    start
+}
+
 case "$1" in
     start)
         start
@@ -83,8 +116,11 @@ case "$1" in
     status)
 	status
         ;;
+    reset)
+	reset
+        ;;
     *)
-        echo "Usage: $0 {start|stop|force-reload|restart|reload|status}"
+        echo "Usage: $0 {start|stop|force-reload|restart|reload|status|reset}"
         exit 1
         ;;
 esac
diff --git a/meta-openstack/recipes-devtools/python/python-glance/glance.init b/meta-openstack/recipes-devtools/python/python-glance/glance.init
--- a/meta-openstack/recipes-devtools/python/python-glance/glance.init
+++ b/meta-openstack/recipes-devtools/python/python-glance/glance.init
@@ -70,6 +70,30 @@ status()
     echo "$DESC is not running"
 }
 
+reset()
+{
+    . /etc/nova/openrc
+
+    # Cleanup all glance images
+    simple_delete "glance image-list --all-tenant" "glance image-delete" 1 "glance image"
+
+    stop
+
+    # This is to make sure postgres is configured and running
+    if ! pidof postmaster > /dev/null; then
+       /etc/init.d/postgresql-init
+       /etc/init.d/postgresql start
+       sleep 5
+    fi
+
+    [ ! -d /var/log/glance ] && mkdir /var/log/glance
+    sudo -u postgres dropdb glance
+    sudo -u postgres createdb glance
+    glance-manage db_sync
+
+    start
+}
+
 case "$1" in
     start)
         start
@@ -84,8 +108,11 @@ case "$1" in
     status)
 	status
         ;;
+    reset)
+	reset
+        ;;
     *)
-        echo "Usage: $0 {start|stop|force-reload|restart|reload|status}"
+        echo "Usage: $0 {start|stop|force-reload|restart|reload|status|reset}"
         exit 1
         ;;
 esac
